# This is a basic workflow to help you get started with Actions

name: Deploy to server

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.16.0
      - name: checkout code
        uses: actions/checkout@v2
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.1.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: asternight.site
          ssh-port: 22
      - name: Deploy to server
        run: |
          npm install -g hexo-cli
          npm install
          hexo g -d
        
      
