# This is a basic workflow to help you get started with Actions

name: Deploy to server

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.14.0
      - name: checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.1.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: asternight.site
          ssh-port: 22
      - name: Deploy to server
        run: |
          npm install -g hexo-cli
          npm install
          git config --global user.email "klxjt99@outlook.com"
          git config --global user.name "AsterNighT"
          hexo g -d --debug
        
      
